swagger: '2.0'
info:
  description: ''
  version: 0.0.1
  title: Pontua
  termsOfService: ''
host: 'localhost:8080'
basePath: /pontua
tags:
  - name: pontua
    description: Pontos em compras
schemes:
  - http
paths:
  /login/cliente:
    post:
      tags:
        - cliente login
      summary: login
      description: ''
      operationId: loginCliente
      produces:
        - application/json
      parameters:
        - name: email
          in: query
          description: email para login
          required: true
          type: string
        - name: senha
          in: query
          description: Senha em texto puro
          required: true
          type: string
      responses:
        '200':
          description: ' retorna token'
          schema:
            type: string
          headers:
            token:
              type: string
              description: token gerado pelo servidor
        '400':
          description: Email ou senha invalidos
  /login/representante:
    post:
      tags:
        - cliente login
      summary: login
      description: ''
      operationId: loginRepresentante
      produces:
        - application/json
      parameters:
        - name: email
          in: query
          description: email para login
          required: true
          type: string
        - name: senha
          in: query
          description: Senha em texto puro
          required: true
          type: string
      responses:
        '200':
          description: retorna token
          schema:
            type: string
          headers:
            token:
              type: string
              description: token gerado pelo servidor
        '400':
          description: Email ou senha invalidos
  /logout/cliente:
    post:
      tags:
        - logout cliente
      summary: ''
      description: ''
      operationId: logoutCliente
      produces:
        - application/json
      parameters:
        - name: token
          in: query
          description: token a ser destruido pelo servidor
          required: true
          type: string
      responses:
        default:
          description: logout ok
  /logout/representante:
    post:
      tags:
        - logout represante
      summary: ''
      description: ''
      operationId: logoutRepresentante
      produces:
        - application/json
      parameters:
        - name: token
          in: query
          description: token a ser destruido pelo servidor
          required: true
          type: string
      responses:
        default:
          description: logout ok
