swagger: '2.0'
info:
  title: Pontua
  version: "0.1"
basePath: /pontua
tags:
  - name: pontua
    description: Pontos em compras
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  
  /login:
    post:
      tags: [Login]
      summary: Return token
      operationId: controller.Login.login
      produces:
       - application/json
      parameters:
        - name: login
          in: body
          schema:
            $ref: '#/definitions/Login'
      responses:
        200:
          description: secret response
          schema:
            type: string
      security:
        - basic: []
  /logout:
    delete:
      tags: [logout]
      summary: ''
      description: ''
      operationId: controller.Login.logout
      responses:
        default:
          description: logout ok
      security:
        - apiKey: []
securityDefinitions:
  basic:
    type: basic
    description: HTTP Basic Authentication.
  apiKey:
    name: apiKey
    type: apiKey
    in: query
    description: API Key 
parameters:
  promocao_id:
    name: promocao_id
    description: Pet's Unique identifier
    in: path
    type: integer
    required: true
    pattern: "^[a-zA-Z0-9-]+$"



definitions:
  Login:
    type: object
    required:
      - email
      - senha
    properties:
      email:
        type: string
        description: email valido
        example: "lc.pg@hotmail.com"
      senha:
        type: string
        description: senha em texto puro
        example: "654321"
